### ISSUE TITLE
Feature request: Proxy support.

### ISSUE THREAD

**Issue by archhaze24** [FyraLabs/skiff-desktop#14]
I live in a country where Skiff is blocked. I use a Tor proxy to bypass censorship, but it is not supported in this app, so I can't access Skiff from it.

**Comment by lleyton** [comment]
Heya, thanks for reaching out. I don't know if you heard the news, after all, Skiff is blocked in your country. However, Skiff got bought out by Notion.. yeah. As such, we aren't updating the desktop app anymore. Please see the following for more context:
- https://skiff.com/data-migration
- https://www.notion.so/blog/meet-skiff-the-newest-member-of-the-notion-family

TL;DR: you have 11 months to get your data out

**Comment by archhaze24** [comment]
Ok, thanks for the info.
