### ISSUE TITLE
App does not load after log-in, infinite loop

### ISSUE THREAD

**Issue by paulie-g** [FyraLabs/skiff-desktop#2]
After logging in, app displays progress circle forever. Console produces numerous errors, the notable ones being:

Right at the top of each load cycle:
```
[Error] XMLHttpRequest cannot load https://api.skiff.com/graphql due to access control checks.
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:886001)
	Promise
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:883721)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:895096)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:891271)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:757185)
	o (2722.37d80aa1789562fcdde6.js:2:757349)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:1378084)
	e (2722.37d80aa1789562fcdde6.js:2:1473555)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:1474482)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:1284538)
	e (2722.37d80aa1789562fcdde6.js:2:1473555)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:1474482)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:1381143)
	(anonymous function) (2722.37d80aa1789562fcdde6.js:2:1381398)```

Then:
```
[Error] Cannot load script https://app.skiff.com/mail/push/push-sw.js. Failed integrity metadata check. Content length: 718, Expected content length: 0, Expected metadata: sha384-J4iz2y3DwTqtrjbRwRQhCu75Ws9nBrUTZ6ASftNaLY7Tzj8qZjfFNzHCvbsaSrZl
```

Downloading it manually, its length is exactly 718; why would it be expected to be 0? That makes no sense. SHA is not defined for 0-length strings anyway.

Then dozens of the following:
```
[Error] Cannot load blob:https://app.skiff.com/2533e3e8-2036-47ee-a36a-9b1f47d78d8d due to access control checks.
	(anonymous function) (skemail-5564.5c474b8ec051cfa789a0.js:75:767179)
	(anonymous function) (skemail-5564.5c474b8ec051cfa789a0.js:75:1444178)
```

Presumably this is some CORS-related breakage?

**Comment by lleyton** [comment]
Sorry for the late response. Taking a look into this now.

**Comment by lleyton** [comment]
Did some debugging, this seems reproducible in Epiphany as well. This seems like some larger issue.
