### ISSUE TITLE
Skiff Mail for Linux attachment issue

### ISSUE THREAD

**Issue by abacaxi33** [FyraLabs/skiff-desktop#6]
Issue in Skiff Mail for Linux Mint Flathub version. I cannot download photos that are in my emails. In an open email the download dialogue does not work, I do not get a prompt where to download. I can open the photo but the new download dialogue does not work either and right click on the photo does not work, too. See attached 2 screenshots with arrows. I use Linux Mint 21.2 Cinnamon, Kernel: 5.15.0-91-generic x86_64 bit, Victoria base: Ubuntu 22.04 jammy Thanks for your comments
![1](https://github.com/FyraLabs/skiff-desktop/assets/137309306/ee57911b-19c7-4c82-b171-8241d482c4c0)
![2](https://github.com/FyraLabs/skiff-desktop/assets/137309306/a11c90c2-cd8c-40c0-95d9-f6ea5bf07617)

**Comment by lleyton** [comment]
confirmed, should be fixed in the latest commit, will push an update soon

**Comment by lleyton** [comment]
just bumped the flathub repo, might take a bit for the update to show up
